version: '3.0'

services:
  db:
    image: 'postgres:16-alpine3.19'
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: questions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    image: 'cotarius/questions:0.1.21'
    #    env_file:
    #      - .env
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - 'GOOGLE_CLIENT_ID=105117623295-9n3bd4job49hggm6jl198jufqta8372b.apps.googleusercontent.com'
      - 'GOOGLE_CLIENT_SECRET=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'
      - 'YANDEX_CLIENT_ID=7b0ded92dc6f45a28b4c877576b52909'
      - 'YANDEX_CLIENT_SECRET=f9a92ec709d94d948b3b4751d7a5b543'
      - 'YANDEX_REDIRECT_URI=https://neocoder.su/login/oauth2/code/yandex'
      - 'TZ=Europe/Moscow'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/questions'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'TELEGRAM_TOKEN=5982691328:AAFalCNB5LRCPDU-nRxL_-RGxK3tnl5Sz3o'
      - 'TELEGRAM_CHAT_ID=1212558248'

volumes:
  data:
    driver: local
