spring:
  application:
    name: Question
  datasource:
    url: jdbc:postgresql://localhost:5432/questionsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 105117623295-9n3bd4job49hggm6jl198jufqta8372b.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
        #            redirect-uri: https://neocoder.su/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
