GOOGLE_CLIENT_ID: 105117623295-9n3bd4job49hggm6jl198jufqta8372b.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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
YANDEX_CLIENT_ID: 7b0ded92dc6f45a28b4c877576b52909
YANDEX_CLIENT_SECRET: f9a92ec709d94d948b3b4751d7a5b543
YANDEX_REDIRECT_URI: https://neocoder.su/login/oauth2/code/yandex
SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/questions
SPRING_DATASOURCE_USERNAME: postgres
SPRING_DATASOURCE_PASSWORD: postgres
