CREATE TABLE quiz_questions (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                question VARCHAR NOT NULL,
                                correct_answer VARCHAR NOT NULL,
                                wrong_answer VARCHAR NOT NULL,
                                wrong_answer_2 VARCHAR NOT NULL,
                                wrong_answer_3 VARCHAR NOT NULL
);