INSERT INTO questions (question, answer, theme, is_impotent)
VALUES ('Чем отличается процесс от потока?', '', 'CORE3_MULTITHREADING', false),
       ('В чем разница между классом Thread и интерфейсом Runnable? В каких случаях предпочтительно использовать Thread, а в каких Runnable?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляет собой монитор? Как в Java реализован монитор?', '', 'CORE3_MULTITHREADING', true),
       ('Что такое синхронизация? Какие методы синхронизации существуют в Java?', '', 'CORE3_MULTITHREADING', true),
       ('Какое значение имеет ключевое слово synchronized? Где и для каких целей его следует использовать?', '', 'CORE3_MULTITHREADING', false),
       ('Какой объект является монитором для статического synchronized-метода?', '', 'CORE3_MULTITHREADING', false),
       ('Какой объект является монитором для нестатического synchronized-метода?', '', 'CORE3_MULTITHREADING', false),
       ('Как действуют методы wait(), notify() и notifyAll() в контексте многопоточности?', '', 'CORE3_MULTITHREADING', false),
       ('В каких состояниях может находиться поток?', '', 'CORE3_MULTITHREADING', false),
       ('Что такое семафор? Как его можно реализовать в Java?', '', 'CORE3_MULTITHREADING', false),
       ('Какое значение имеет ключевое слово volatile? Почему операции с volatile переменными не являются атомарными?', '', 'CORE3_MULTITHREADING', false),
       ('Зачем нужны атомарные (Atomic) типы данных? В чем отличие от переменных с ключевым словом volatile?', '', 'CORE3_MULTITHREADING', true),
       ('Что представляют собой демон-потоки? Какова их роль и как создать демон-поток?', '', 'CORE3_MULTITHREADING', false),
       ('Что такое приоритет потока? Как он влияет на выполнение потока? Какой приоритет у потоков по умолчанию?', '', 'CORE3_MULTITHREADING', false),
       ('Как работает метод Thread.join()? Для чего он используется?', '', 'CORE3_MULTITHREADING', false),
       ('В чем разница между методами wait() и sleep()?', '', 'CORE3_MULTITHREADING', false),
       ('Можно ли вызвать start() для одного потока дважды?', '', 'CORE3_MULTITHREADING', false),
       ('Как правильно остановить поток? Какие методы .stop(), .interrupt(), .interrupted(), .isInterrupted() используются и для каких целей?', '', 'CORE3_MULTITHREADING', false),
       ('В чем различия между интерфейсами Runnable и Callable?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляет собой FutureTask?', '', 'CORE3_MULTITHREADING', false),
       ('Что такое deadlock (взаимная блокировка)?', '', 'CORE3_MULTITHREADING', true),
       ('Что такое livelock? Как он отличается от deadlock?', '', 'CORE3_MULTITHREADING', true),
       ('Что представляет собой race condition?', '', 'CORE3_MULTITHREADING', true),
       ('Что такое фреймворк fork/join? Какова его роль и назначение?', '', 'CORE3_MULTITHREADING', false),
       ('Что входит в java.util.concurrent?', '', 'CORE3_MULTITHREADING', true),
       ('Что такое Executor в контексте пакета java.util.concurrent?', '', 'CORE3_MULTITHREADING', false),
       ('Как создать и использовать пул потоков с помощью ExecutorService?', '', 'CORE3_MULTITHREADING', false),
       ('Как использовать CountDownLatch для ожидания завершения определенного числа задач?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляет собой CyclicBarrier и в каких сценариях он может быть полезен?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляют собой классы ReentrantLock и ReentrantReadWriteLock?', '', 'CORE3_MULTITHREADING', false),
       ('Как работает Phaser и для чего может быть использован?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляет собой ConcurrentHashMap и где используется?', '', 'CORE3_MULTITHREADING', false),
       ('Что представляет собой ThreadLocal и где используется?', '', 'CORE3_MULTITHREADING', false),
       ('Как связаны Stream API и ForkJoinPool? Что представляют из себя?', '', 'CORE3_MULTITHREADING', false),
       ('Что такое Java Memory Model?', '', 'CORE3_MULTITHREADING', false),
       ('Что такое reordering, happens-before и область видимости?', '', 'CORE3_MULTITHREADING', false);